Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
